{% set name = "libacl" %}
{% set version = "2.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: http://download.savannah.gnu.org/releases/acl/acl-{{ version }}.tar.xz
    sha256: e661131456d2708a01c614a0f400e11d7d1bfaeb6f3e74b75bb980b72f0161a3

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - autoconf
    - make
  host:
    - attr

test:
  commands:
    - test -f ${PREFIX}/include/sys/acl.h

about:
  home: https://savannah.nongnu.org/projects/acl/
  license: GPL-2.0-or-later
  license_file: doc/COPYING
  summary: Commands for Manipulating POSIX Access Control Lists

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - wolfv
