{% set name = "libacl" %}
{% set version = "2.3.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: http://download.savannah.gnu.org/releases/acl/acl-{{ version }}.tar.xz
    sha256: 97203a72cae99ab89a067fe2210c1cbf052bc492b479eca7d226d9830883b0bd

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - make
  host:
    - attr

test:
  commands:
    - test -f ${PREFIX}/include/sys/acl.h

about:
  home: https://savannah.nongnu.org/projects/acl/
  license: GPL-2.0-or-later
  license_file: doc/COPYING
  summary: Commands for Manipulating POSIX Access Control Lists

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - wolfv
